### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by dogaakcinar** [orchidas/Speaker-Recognition#1]
Hi, i read your documentation and that was really good.Thanks for your work it's impressive.
I cloned the repo to my Ubuntu 14.04 and when i run the test.py it causes an error like that:
`Now speaker  1 features are being trained
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    (codebooks_mfcc, codebooks_lpc) = training(nfiltbank, orderLPC)
  File "/home/dogakcinar/Desktop/Speaker-Recognition-master/train.py", line 30, in training
    mel_coeff = mfcc(s, fs, nfiltbank)
  File "/home/dogakcinar/Desktop/Speaker-Recognition-master/mel_coefficients.py", line 73, in mfcc
    periodogram = np.empty((nFrames,nfft/2 + 1))
TypeError: 'float' object cannot be interpreted as an index
`

**Comment by orchidas** [comment]
It seems there is a probem with nfft/2, maybe try changing the value of nfft to a power of 2?
